/*
 * app_config.h
 *
 *  Created on: Sep 27, 2026
 *      Author: jpser
 *
 *  Every tunable of the ground speed sensor lives here. Pins are NOT here:
 *  they come from the .ioc labels (main.h, generated by CubeMX).
 *
 *  Port of the Teensy 4.0 firmware from "Design and Prototyping of an Optical
 *  Non-contact Ground Speed Sensor for a Race Car" (Chalmers, 2025), original
 *  code by Milton Runberger & David Spaberg, licensed CC BY-NC-SA 4.0:
 *  https://github.com/spaberg/Optical-Ground-Speed-Sensor
 */

#ifndef INC_APP_CONFIG_H_
#define INC_APP_CONFIG_H_

/* ======================================================================== */
/*  CAN protocol (port of CAN_interface.cpp)                                */
/* ======================================================================== */
/*
 * One standard 11-bit ID is used for everything, like the Teensy (sensor_id).
 * Byte 0 of every frame is the command / message type.
 *
 * Received by the sensor (StdId = CAN_SENSOR_ID):
 *   buf[0] = 110  ENABLE_SPEED   buf[1] = interval [ms] (0 = keep current)
 *   buf[0] = 100  DISABLE_SPEED
 *   buf[0] = 210  ENABLE_IMAGE   buf[1] = interval [ms] (0 = keep current)
 *   buf[0] = 200  DISABLE_IMAGE
 *
 * Sent by the sensor (StdId = CAN_SENSOR_ID, DLC 8):
 *   SEND_SPEED (101):
 *     buf[0]   = 101
 *     buf[1:2] = vx  int16 little endian, 0.01 m/s  (raw counts if CAN_SPEED_PAYLOAD_RAW_COUNTS)
 *     buf[3:4] = vy  int16 little endian, 0.01 m/s  (raw counts if CAN_SPEED_PAYLOAD_RAW_COUNTS)
 *     buf[5]   = height used for scaling [mm], 0xFF = n/a
 *     buf[6]   = status bits (CAN_STATUS_*)
 *     buf[7]   = rolling counter
 *   SEND_IMAGE (201), one 36x36 frame = 216 frames:
 *     buf[0]   = 201
 *     buf[1]   = chunk index 0..215 (0 = start of a new image)
 *     buf[2:7] = 6 pixels, row major
 */
#define CAN_SENSOR_ID                   69u     // 0x045, same as Teensy sensor_id

#define CAN_CMD_ENABLE_SPEED            110u
#define CAN_CMD_DISABLE_SPEED           100u
#define CAN_CMD_ENABLE_IMAGE            210u
#define CAN_CMD_DISABLE_IMAGE           200u
#define CAN_MSG_SEND_SPEED              101u
#define CAN_MSG_SEND_IMAGE              201u

#define CAN_STATUS_PAW_OK               0x01u   // displacement sensor answered at init and last read was OK
#define CAN_STATUS_TOF_OK               0x02u   // VL6180X height sensor has a fresh valid range
#define CAN_STATUS_HEIGHT_MEASURED      0x04u   // speed scaled with measured height (else fixed)
#define CAN_STATUS_IMAGE_ACTIVE         0x08u   // an image is being streamed (speed samples paused during grab)

#define CAN_SPEED_INTERVAL_DEFAULT_MS   10u     // 100 Hz, Teensy default
#define CAN_IMAGE_INTERVAL_DEFAULT_MS   41u     // Teensy default (>24 FPS asked, bus limits it to ~8 FPS @ 500k)

/* 1 = stream speed from power up. Teensy waited for ENABLE_SPEED (= 0). */
#define CAN_SPEED_STREAM_AT_BOOT        1

/* 1 = bytes 1..4 carry raw PAW counts accumulated since the last frame (Teensy behaviour).
 * 0 = bytes 1..4 carry the computed speed in 0.01 m/s (the Teensy TODO). */
#define CAN_SPEED_PAYLOAD_RAW_COUNTS    0

/* 1 = print every received command frame on the debug UART (debug_incomming_message) */
#define CAN_DEBUG_RX_PRINT              1

#define CAN_TX_QUEUE_LEN                64u     // software TX queue, power of 2
#define CAN_RX_QUEUE_LEN                16u     // software RX queue, power of 2
#define CAN_TX_STUCK_TIMEOUT_MS         100u    // abort mailboxes nobody ACKs for this long (no node on the bus)

/* ======================================================================== */
/*  Displacement sensor PAW3395DM-T6QU + speed calculation                  */
/* ======================================================================== */
#define GSS_SAMPLE_PERIOD_US            10000u  // 100 Hz, Teensy loop delay(10)
#define GSS_MM_PER_COUNT                0.00508f // cpi_to_mm_factor (5000 CPI)
#define GSS_LIFT_CUTOFF_2MM             1       // lift_cutoff_2mm() at init

/* Height used in the speed formula */
#define GSS_HEIGHT_FIXED                0       // always GSS_HEIGHT_MM (Teensy: HEIGHT_MM 80)
#define GSS_HEIGHT_MEASURED             1       // VL6180X range, falls back to GSS_HEIGHT_MM when invalid
#define GSS_HEIGHT_SOURCE               GSS_HEIGHT_FIXED
#define GSS_HEIGHT_MM                   80.0f

/* Height -> scale factor
 *   LINEAR : scale = h * GSS_LINEAR_GAIN              (Teensy get_speed(): simple_height_speed_scaling = 1 * height)
 *   POLY   : scale = A*h^2 + B*h + C                  (fit of Scripts/fit_height_curve.py data, thesis rig optics)
 * speed [m/s] = scale * counts * GSS_MM_PER_COUNT / dt [ms]
 */
#define GSS_SCALE_LINEAR                0
#define GSS_SCALE_POLY                  1
#define GSS_SCALE_MODE                  GSS_SCALE_LINEAR
#define GSS_LINEAR_GAIN                 1.0f
#define GSS_POLY_A                      (-1.5548472e-4f)
#define GSS_POLY_B                      (3.89372902e-1f)
#define GSS_POLY_C                      (1.74291411f)

/* Exponential filter on the speed output, 1.0 = no filter (Teensy) */
#define GSS_SPEED_FILTER_ALPHA          1.0f

/* ======================================================================== */
/*  Height sensor VL6180X (port of Height_sensor.cpp / Adafruit_VL6180X)    */
/* ======================================================================== */
#define HEIGHT_SENSOR_ENABLE            1
#define HEIGHT_RANGE_PERIOD_MS          20u     // one single-shot range every 20 ms
#define HEIGHT_ALS_EVERY_N_RANGES       25u     // one lux reading (100 ms integration) every N ranges
#define HEIGHT_VALID_TIMEOUT_MS         200u    // range older than this = invalid
#define HEIGHT_ALS_GAIN                 VL6180X_ALS_GAIN_5 // Teensy: readLux(VL6180X_ALS_GAIN_5)

/* ======================================================================== */
/*  NeoPixel ring (24x WS2812, Teensy pin 14)                               */
/* ======================================================================== */
#define LED_RING_NUM_PIXELS             24u
#define LED_RING_ON_AT_BOOT             0       // Teensy: turn_on_pixel_ring() was commented out
#define LED_RING_BOOT_R                 255u
#define LED_RING_BOOT_G                 255u
#define LED_RING_BOOT_B                 255u
#define LED_RING_BOOT_BRIGHTNESS        255u

/* ======================================================================== */
/*  Debug UART (USART2) streaming, replaces Teensy Serial prints            */
/* ======================================================================== */
#define SERIAL_STREAM_OFF               0
#define SERIAL_STREAM_CSV               1       // t_ms,dx,dy,vx,vy,h_mm,range_mm,lux,squal per sample
#define SERIAL_STREAM_DISPLACEMENT      2       // "dx,dy"  (print_displacement)
#define SERIAL_STREAM_SPEED_X           3       // "vx"     (get_speed(..., debug = true))
#define SERIAL_STREAM_IMAGE             4       // 1296 CSV pixels + "dx,dy" (Scripts/image_and_displacement.py)
#define SERIAL_STREAM_MODE              SERIAL_STREAM_CSV
#define SERIAL_STREAM_IMAGE_PERIOD_MS   100u

#define DEBUG_UART_TX_BUF_SIZE          8192u   // power of 2
#define DEBUG_UART_BLOCK_TIMEOUT_MS     20u     // max wait for room in the TX buffer, then drop

/* ======================================================================== */
/*  Status LEDs                                                             */
/* ======================================================================== */
#define HEARTBEAT_PERIOD_MS             500u

#endif /* INC_APP_CONFIG_H_ */
